      - name: Pull FB Ads basic (existing)
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FB_AD_ACCOUNT_ID: ${{ secrets.FB_AD_ACCOUNT_ID }}
          FB_API_VER: "v20.0"
          FB_LOOKBACK_DAYS: "7"
          FB_OUT_FILE: "analytics/dataprocessed/facebook_live_ads.csv"
        run: python analytics/scripts/facebook_ads_pull.py

      - name: Pull FB Ads full metadata + breakdowns
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FB_AD_ACCOUNT_ID: ${{ secrets.FB_AD_ACCOUNT_ID }}
          FB_API_VER: "v20.0"
          FB_LOOKBACK_DAYS: "7"
        run: python analytics/scripts/facebook_ads_full_pull.py
