name: Marketing Data Pipeline

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  facebook-ads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Ensure output folder exists
        run: mkdir -p analytics/dataprocessed

      - name: Pull Facebook Ads
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FB_AD_ACCOUNT_ID: ${{ secrets.FB_AD_ACCOUNT_ID }}
          FB_API_VER: "v20.0"
          FB_LOOKBACK_DAYS: "7"
          FB_OUT_FILE: "analytics/dataprocessed/facebook_live_ads.csv"
        run: python analytics/scripts/facebook_ads_pull.py

      - name: Commit CSV if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add analytics/dataprocessed/facebook_live_ads.csv
          git commit -m "update fb csv" || echo "no changes"
          git push
