name: Marketing Data Pipeline
on:
  schedule:
    - cron: "0 10 * * *"   # daily 10:00 UTC
  workflow_dispatch: {}

jobs:
  facebook-ads:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Facebook Ads pull
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FB_AD_ACCOUNT_ID: ${{ secrets.FB_AD_ACCOUNT_ID }}
          FB_API_VER: v20.0
          FB_LOOKBACK_DAYS: "7"
          FB_OUT_FILE: analytics/dataprocessed/facebook_live_ads.csv
        run: |
          python analytics/scripts/facebook_ads_pull.py

      - name: Commit updated CSV
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p analytics/dataprocessed
          git add analytics/dataprocessed/facebook_live_ads.csv || true
          git diff --cached --quiet && echo "No changes" || git commit -m "update: facebook_live_ads.csv"
          git push
